test:
  tags:     ON
  captcha:  ON
  sphinx:   OFF
  worker:   OFF

development:
  tags:     ON
  captcha:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.development.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'
  data2pdf: ON

production:
  tags:     ON
  captcha:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.production.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'
  data2pdf: ON
